spring:
  application:
    name: platform.training.bookmiddle
    version: 1.0.0
  jackson:
    default-property-inclusion: non_null

swagger:
  title: BookMiddle Service REST APIs
  description: This successfully showcased Spring Boot REST API
  contact:
    name: Michael
    url: http://www.ebsco.com
    email: mpanson@ebsco.com
  version: 1.0.0

book:
  includeChildrens: true
  useStubs: false

---

spring:
  profiles: local

book:
  includeChildrens: false
  useStubs: true
  stubSettings:
    number: 5
    staticAuthor: "Author McBook"
    staticTitle: "Test Book"
    staticGenre: "Training"