spring:
  application:
    name: platform.training.bookmiddle
    version: 1.0.0
  jackson:
    default-property-inclusion: non_null

server:
  port: ${service.port:8080}

swagger:
  title: BookMiddle Service REST APIs
  description: This successfully showcased Spring Boot REST API
  contact:
    name: Michael
    url: http://www.ebsco.com
    email: mpanson@ebsco.com
  version: 1.0.0

eureka:
  instance:
    # This is the Eureka VIP (virtual IP, like a DNS name for addressability during discovery)
    instanceId: ${spring.application.name}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka.vpca.us-east-1.eis-delivery${AWS_ENV}.cloud:8761/eureka/
  aws:
    registration:
      enabled: true

---

spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.url:http://localhost:8761/eureka/}
  aws:
    registration:
      enabled: false

---