spring:
  application:
    name: platform.training.bookmiddle
    version: 1.0.0
  jackson:
    default-property-inclusion: non_null

swagger:
  title: BookMiddle Service REST APIs
  description: This successfully showcased Spring Boot REST API
  contact:
    name: Michael

    url: http://www.ebsco.com
    email: mpanson@ebsco.com
  version: 1.0.0

# Enable metrics collection and DataDog reporter
metric:
  enabled: true
  datadog:
    reporter:
      enabled: true

# Enable /metrics endpoint for service
# Often disabled since we send to DataDog
management:
  security:
    enabled: false
