spring:
  application:
    name: platform.training.bookmiddle
    version: 1.0.0
  jackson:
    default-property-inclusion: non_null

swagger:
  title: BookMiddle Service REST APIs
  description: This successfully showcased Spring Boot REST API
  contact:
    name: Michael
    url: http://www.ebsco.com
    email: mpanson@ebsco.com
  version: 1.0.0

application:
  market: ${APP_MARKET:platform}
  domain: ${APP_DOMAIN:training}
  subenv: ${APP_SUB_ENV:subenv}
  environment: ${AWS_ENV:local}
  containerId: ${HOSTNAME:container}
  transactionIdHeader: "TRANSACTION_ID"